name: Auto Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: 🧰 Instalar Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy div folder to private repo
        run: |
          cd dist
          git init
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git remote add origin https://x-access-token:${{ secrets.SSH_PRIVATE_KEY }}@github.com/eletroswing/portifolio_build.git
          git branch -M main
          git add .
          git commit -m "Auto deploy from workflow"
          git config pull.rebase true
          git pull origin main
          git push -f origin main
